#!/usr/bin/env node

/**
 * プリビルドスクリプト: Spec YAMLファイルのバンドル生成
 *
 * このスクリプトは、ビルド時に実行され、YAMLファイルから
 * TypeScriptモジュールを生成します。Cloudflare Workersでは
 * ファイルシステムアクセスができないため、ビルド時にコンテンツを
 * バンドルする必要があります。
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '../..');

/**
 * Spec YAMLファイルをバンドルする
 */
async function generateSpecs() {
  try {
    console.log('🚀 Starting specs generation...');

    const specsDir = path.join(rootDir, 'app/specs');
    const outputPath = path.join(rootDir, 'app/generated/specs.ts');

    // 1. app/specs配下のすべてのYAMLファイルを読み込む
    const specs = {};
    const services = await fs.readdir(specsDir);

    for (const service of services) {
      const servicePath = path.join(specsDir, service);
      const stat = await fs.stat(servicePath);

      if (!stat.isDirectory()) continue;

      const files = await fs.readdir(servicePath);
      const yamlFiles = files.filter(file => file.endsWith('-spec.yaml'));

      for (const file of yamlFiles) {
        const sectionName = file.replace('-spec.yaml', '');
        const featurePath = `${service}/${sectionName}`;
        const specPath = path.join(servicePath, file);

        try {
          const yamlString = await fs.readFile(specPath, 'utf-8');
          const parsedSpec = yaml.load(yamlString);
          specs[featurePath] = parsedSpec;
          console.log(`   ✅ Loaded spec: ${featurePath}`);
        } catch (error) {
          console.error(`   ❌ Failed to load spec ${featurePath}:`, error.message);
        }
      }
    }

    console.log(`📝 Found ${Object.keys(specs).length} spec files`);

    // 2. TypeScriptファイルを生成
    const tsContent = `// Auto-generated by scripts/prebuild/generate-specs.js
// Do not edit manually - this file is regenerated on every build

/**
 * Spec データ（ビルド時生成）
 *
 * このファイルは、ビルド時にYAMLファイルから自動生成されます。
 * Cloudflare Workersではファイルシステムアクセスができないため、
 * ビルド時にすべてのspecをバンドルしています。
 */

const specs: Record<string, unknown> = ${JSON.stringify(specs, null, 2)};

/**
 * 指定された機能パスに対応するspecを取得する
 * @param featurePath 'blog/posts' のような機能パス
 * @returns パース済みのSpecオブジェクト
 */
export function getSpec<T>(featurePath: string): T {
  if (!specs[featurePath]) {
    throw new Error(\`Spec not found for feature: \${featurePath}\`);
  }
  return specs[featurePath] as T;
}

/**
 * 読み込まれているすべてのspec機能パスを取得
 */
export function getAllSpecPaths(): string[] {
  return Object.keys(specs);
}
`;

    // 3. 出力ディレクトリを作成
    const outputDir = path.dirname(outputPath);
    await fs.mkdir(outputDir, { recursive: true });

    // 4. ファイルを書き出し
    await fs.writeFile(outputPath, tsContent, 'utf-8');
    console.log(`✅ Generated ${outputPath}`);

    console.log('\n✨ Specs generation completed successfully!');
    console.log(`\n📊 Summary:`);
    console.log(`   - Specs: ${Object.keys(specs).length}`);
  } catch (error) {
    console.error('❌ Failed to generate specs:', error);
    process.exit(1);
  }
}

// スクリプトを実行
generateSpecs();
