#!/usr/bin/env node

/**
 * プリビルドスクリプト: Spec YAMLファイルのバンドル生成
 *
 * このスクリプトは、ビルド時に実行され、YAMLファイルから
 * TypeScriptモジュールを生成します。Cloudflare Workersでは
 * ファイルシステムアクセスができないため、ビルド時にコンテンツを
 * バンドルする必要があります。
 */

import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import yaml from 'js-yaml';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.join(__dirname, '../..');

/**
 * Spec YAMLファイルをバンドルする
 */
async function generateSpecs() {
  try {
    console.log('🚀 Starting specs generation...');

    const specsDir = path.join(rootDir, 'app/specs');
    const outputPath = path.join(rootDir, 'app/generated/specs.ts');

    // 1. app/specs配下のすべてのYAMLファイルを読み込む
    const specs = {};
    const sharedSpecs = {};
    const services = await fs.readdir(specsDir);

    for (const service of services) {
      const servicePath = path.join(specsDir, service);
      const stat = await fs.stat(servicePath);

      if (!stat.isDirectory()) continue;

      const files = await fs.readdir(servicePath);
      const yamlFiles = files.filter(file => file.endsWith('-spec.yaml'));

      for (const file of yamlFiles) {
        const specPath = path.join(servicePath, file);

        try {
          const yamlString = await fs.readFile(specPath, 'utf-8');
          const parsedSpec = yaml.load(yamlString);

          // sharedディレクトリの場合は別管理
          if (service === 'shared') {
            const specName = file.replace('-spec.yaml', '').replace('project-', ''); // 'project-spec.yaml' -> 'project'
            sharedSpecs[specName] = parsedSpec;
            console.log(`   ✅ Loaded shared spec: ${specName}`);
          } else {
            const sectionName = file.replace('-spec.yaml', '');
            const featurePath = `${service}/${sectionName}`;
            specs[featurePath] = parsedSpec;
            console.log(`   ✅ Loaded spec: ${featurePath}`);
          }
        } catch (error) {
          console.error(`   ❌ Failed to load spec ${specPath}:`, error.message);
        }
      }
    }

    console.log(`📝 Found ${Object.keys(specs).length} section specs`);
    console.log(`📝 Found ${Object.keys(sharedSpecs).length} shared specs`);

    // 2. TypeScriptファイルを生成
    const tsContent = `// Auto-generated by scripts/prebuild/generate-specs.js
// Do not edit manually - this file is regenerated on every build

/**
 * Spec データ（ビルド時生成）
 *
 * このファイルは、ビルド時にYAMLファイルから自動生成されます。
 * Cloudflare Workersではファイルシステムアクセスができないため、
 * ビルド時にすべてのspecをバンドルしています。
 */

/**
 * セクションspec（サービス/セクション単位）
 */
const specs: Record<string, unknown> = ${JSON.stringify(specs, null, 2)};

/**
 * 共通spec（サービス横断）
 */
const sharedSpecs: Record<string, unknown> = ${JSON.stringify(sharedSpecs, null, 2)};

/**
 * セクションspecを取得
 * @param featurePath 'blog/posts' のような機能パス
 * @returns パース済みのSpecオブジェクト
 */
export function getSpec<T>(featurePath: string): T {
  if (!specs[featurePath]) {
    throw new Error(\`Spec not found for feature: \${featurePath}\`);
  }
  return specs[featurePath] as T;
}

/**
 * 共通specを取得
 * @param specName 'validation', 'responsive', 'server', 'project' のいずれか
 * @returns パース済みのSharedSpecオブジェクト
 */
export function getSharedSpec<T>(specName: string): T {
  if (!sharedSpecs[specName]) {
    throw new Error(\`Shared spec not found: \${specName}\`);
  }
  return sharedSpecs[specName] as T;
}

/**
 * 読み込まれているすべてのspec機能パスを取得
 */
export function getAllSpecPaths(): string[] {
  return Object.keys(specs);
}

/**
 * 読み込まれているすべての共通spec名を取得
 */
export function getAllSharedSpecNames(): string[] {
  return Object.keys(sharedSpecs);
}
`;

    // 3. 出力ディレクトリを作成
    const outputDir = path.dirname(outputPath);
    await fs.mkdir(outputDir, { recursive: true });

    // 4. ファイルを書き出し
    await fs.writeFile(outputPath, tsContent, 'utf-8');
    console.log(`✅ Generated ${outputPath}`);

    console.log('\n✨ Specs generation completed successfully!');
    console.log(`\n📊 Summary:`);
    console.log(`   - Section specs: ${Object.keys(specs).length}`);
    console.log(`   - Shared specs: ${Object.keys(sharedSpecs).length}`);
  } catch (error) {
    console.error('❌ Failed to generate specs:', error);
    process.exit(1);
  }
}

// スクリプトを実行
generateSpecs();
